# ABOUTME: Shared services for all VarnaAI apps - PostgreSQL, Redis, Traefik/Cloudflared
# ABOUTME: Use with app-specific compose files via docker-compose -f compose.shared.yml -f compose.app.yml

version: '3.8'

networks:
  web:
    name: web
    driver: bridge
  db:
    name: db
    driver: bridge
  cache:
    name: cache
    driver: bridge

volumes:
  postgres_data:
  redis_data:
  letsencrypt:
  prometheus_data:
  grafana_data:
  loki_data:

services:
  # === DATABASE ===
  postgres:
    image: postgres:15-alpine
    container_name: varnaai_postgres
    restart: unless-stopped
    networks:
      - db
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d:ro
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_DB=${POSTGRES_DB:-varnaai}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '1.0'
    profiles: ["db", "full"]

  # === CACHE ===
  redis:
    image: redis:7-alpine
    container_name: varnaai_redis
    restart: unless-stopped
    networks:
      - cache
    volumes:
      - redis_data:/data
    command: >
      redis-server
      --maxmemory 512mb
      --maxmemory-policy allkeys-lru
      --appendonly yes
      ${REDIS_PASSWORD:+--requirepass ${REDIS_PASSWORD}}
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '0.5'
    profiles: ["cache", "full"]

  # === EDGE PROXY - Option 1: Traefik ===
  traefik:
    image: traefik:v3.0
    container_name: varnaai_traefik
    restart: unless-stopped
    networks:
      - web
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"  # Dashboard - disable in production
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - letsencrypt:/letsencrypt
      - ./traefik:/etc/traefik:ro
    environment:
      - CF_API_EMAIL=${CF_API_EMAIL}
      - CF_API_KEY=${CF_API_KEY}
    command:
      - "--api.dashboard=true"
      - "--api.insecure=${ENVIRONMENT:-demo}"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=web"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.letsencrypt.acme.dnschallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.dnschallenge.provider=cloudflare"
      - "--certificatesresolvers.letsencrypt.acme.email=${CF_API_EMAIL}"
      - "--certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json"
      - "--log.level=${LOG_LEVEL:-INFO}"
      - "--accesslog=true"
    healthcheck:
      test: ["CMD", "traefik", "healthcheck"]
      interval: 10s
      timeout: 5s
      retries: 3
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
    profiles: ["traefik", "full"]

  # === EDGE PROXY - Option 2: Cloudflare Tunnel ===
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: varnaai_cloudflared
    restart: unless-stopped
    networks:
      - web
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN}
    healthcheck:
      test: ["CMD", "cloudflared", "tunnel", "info"]
      interval: 30s
      timeout: 5s
      retries: 3
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.25'
    profiles: ["cloudflared", "secure"]

  # === MONITORING - Prometheus ===
  prometheus:
    image: prom/prometheus:latest
    container_name: varnaai_prometheus
    restart: unless-stopped
    networks:
      - web
      - db
      - cache
    volumes:
      - prometheus_data:/prometheus
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=${PROMETHEUS_RETENTION_TIME:-7d}'
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:9090/-/healthy"]
      interval: 30s
      timeout: 5s
      retries: 3
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '0.5'
    profiles: ["monitoring", "full"]

  # === MONITORING - Grafana ===
  grafana:
    image: grafana/grafana:latest
    container_name: varnaai_grafana
    restart: unless-stopped
    networks:
      - web
    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/grafana/dashboards:/etc/grafana/provisioning/dashboards:ro
      - ./monitoring/grafana/datasources:/etc/grafana/provisioning/datasources:ro
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
      - GF_INSTALL_PLUGINS=grafana-piechart-panel
      - GF_ANALYTICS_REPORTING_ENABLED=false
      - GF_USERS_ALLOW_SIGN_UP=false
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 5s
      retries: 3
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.grafana.rule=Host(`monitor.${DOMAIN_BASE}`)"
      - "traefik.http.routers.grafana.entrypoints=websecure"
      - "traefik.http.routers.grafana.tls.certresolver=letsencrypt"
      - "traefik.http.services.grafana.loadbalancer.server.port=3000"
    profiles: ["monitoring", "full"]

  # === LOGGING - Loki ===
  loki:
    image: grafana/loki:latest
    container_name: varnaai_loki
    restart: unless-stopped
    networks:
      - web
    volumes:
      - loki_data:/loki
      - ./monitoring/loki-config.yml:/etc/loki/local-config.yaml:ro
    command: -config.file=/etc/loki/local-config.yaml
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:3100/ready"]
      interval: 30s
      timeout: 5s
      retries: 3
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '0.5'
    profiles: ["monitoring", "full"]

  # === BACKUP - Restic ===
  backup:
    image: restic/restic:latest
    container_name: varnaai_backup
    restart: unless-stopped
    networks:
      - db
    volumes:
      - postgres_data:/backup/postgres:ro
      - redis_data:/backup/redis:ro
      - ./backup:/scripts:ro
      - /tmp/restic-cache:/cache
    environment:
      - RESTIC_REPOSITORY=s3:s3.amazonaws.com/${S3_BACKUP_BUCKET}
      - RESTIC_PASSWORD=${RESTIC_PASSWORD}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - BACKUP_CRON=${BACKUP_CRON:-0 2 * * *}
    entrypoint: ["/scripts/backup-entrypoint.sh"]
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
    profiles: ["backup", "full"]